

services:
  k3s-server:
    container_name: k3s-server
    image: rancher/k3s:v1.32.1-k3s1  
    command: >-
      server
      --cluster-cidr=10.44.0.0/16 # Cluster CIDR range
    privileged: true
    network_mode: "host"
    environment:
      - .env
    volumes:
      # Named volume for K3s data persistence
      - k3s-server:/var/lib/rancher/k3s 
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    network_mode: "host" 
    volumes:
      # Mount Prometheus configuration file
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_password
    volumes:
      # Named volume for Grafana data persistence
      - grafana-storage:/var/lib/grafana
      # Provisioning configurations
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      # Pre-configured dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  # Stores Grafana configurations and data
  grafana-storage:
  # Stores K3s cluster state and configurations
  k3s-server: 