---
- name: Clean up K3s agents
  hosts: ruglets
  become: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter sudo password"
      private: yes

  tasks:
    - name: Check if k3s-agent service exists
      stat:
        path: /etc/systemd/system/k3s-agent.service
      register: service_file

    - name: Stop K3s agent if service exists
      systemd:
        name: k3s-agent
        state: stopped
      when: service_file.stat.exists
      ignore_errors: yes

    - name: Check if uninstall script exists
      stat:
        path: /usr/local/bin/k3s-agent-uninstall.sh
      register: uninstall_script

    - name: Run uninstall script if it exists
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      when: uninstall_script.stat.exists
      ignore_errors: yes

    - name: Remove K3s directories if they exist
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
        - /var/lib/kubelet
        - /etc/systemd/system/k3s-agent.service.d
      ignore_errors: yes

    - name: Force kill any remaining k3s processes
      shell: |
        pkill -9 k3s || true
        pkill -9 containerd || true
      ignore_errors: yes

    - name: Remove k3s binary if it exists
      file:
        path: /usr/local/bin/k3s
        state: absent
      ignore_errors: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes