---
- name: Clean up K3s agents
  hosts: ruglets
  become: true
  gather_facts: false

  tasks:
    - name: Check for k3s-agent unit file
      stat:
        path: /etc/systemd/system/k3s-agent.service
      register: k3s_unit

    - name: Stop k3s-agent if present
      systemd:
        name: k3s-agent
        state: stopped
      when: k3s_unit.stat.exists
      ignore_errors: true

    - name: Check uninstall script
      stat:
        path: /usr/local/bin/k3s-agent-uninstall.sh
      register: uninstall_script

    - name: Run official uninstall if present
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      register: uninstall_result
      failed_when: false
      changed_when: uninstall_result.rc is defined and uninstall_result.rc == 0
      when: uninstall_script.stat.exists

    - name: Kill lingering k3s/containerd (remove containerd line if Pis run other containers)
      shell: |
        pkill -9 k3s || true
        pkill -9 containerd || true
      changed_when: false
      failed_when: false

    - name: Delete CNI interfaces
      shell: |
        ip link del cni0 2>/dev/null || true
        ip link del flannel.1 2>/dev/null || true
      changed_when: false
      failed_when: false

    - name: Remove unit files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/systemd/system/k3s-agent.service
        - /etc/systemd/system/k3s-agent.service.d
      ignore_errors: true

    - name: Remove leftovers
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/k3s
        - /var/lib/rancher/k3s
        - /var/lib/kubelet
        - /var/lib/cni
        - /etc/cni/net.d
        - /opt/cni/bin
        - /usr/local/bin/k3s
      ignore_errors: true

    - name: Reload systemd
      systemd:
        daemon_reload: true
