---
- name: Install monitoring tools
  hosts: ruglets, rugctl
  become: true
  become_method: sudo
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter sudo password"
      private: yes

  tasks:
    - name: Ensure Node Exporter is running
      systemd:
        name: prometheus-node-exporter
        state: started
        enabled: yes

    - name: Install basic monitoring tools for Ubuntu nodes (ruglets)
      apt:
        name:
          - htop
          - iotop
          - nmon
        state: present
      when: "'ruglet' in inventory_hostname"

    - name: Install basic monitoring tools for Arch (rugctl)
      community.general.pacman:
        name:
          - htop
          - iotop
          - nmon
        state: present
      when: inventory_hostname == "rugctl"
