---
- name: Update and upgrade apt packages on all ruglets
  hosts: ruglets
  become: true
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Enter sudo password"
      private: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: yes
        force_apt_get: yes
      register: upgrade_result

    - name: Remove old packages (autoremove)
      apt:
        autoremove: yes
        purge: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot if required
      reboot:
        msg: "Rebooting due to system updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: reboot_required.stat.exists

    - name: Print reboot status
      debug:
        msg: "System was rebooted"
      when: reboot_required.stat.exists
